<?xml version="1.0"?>
<package format="2">
  <name>random_goals</name>
  <version>0.0.0</version>
  <description>Random GoalSet publisher for the V2 sandbox.</description>

  <maintainer email="guanwen@todo.todo">guanwen</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>nav_msgs</depend>
  <depend>quadrotor_msgs</depend>
  <depend>roscpp</depend>
  <depend>std_msgs</depend>
  <depend>uav_utils</depend>
</package>